#!/usr/bin/env bash
alias vimrc="${EDITOR} ${HOME}/.config/nvim/init.vim"
alias tmux="tmux new-session -ADs main"
alias less="less -r -S -N"
alias zshrc="${EDITOR} ${HOME}/.zshrc"

if command -v caffeinate >/dev/null 2>&1; then
    alias awake="caffeinate -dims"
fi

if command -v bat >/dev/null 2>&1; then
    alias cat=bat
fi

if command -v walk >/dev/null 2>&1; then
    alias wd='cd "$(walk "$@")"'
fi

if command -v eza >/dev/null 2>&1; then
    alias ls=eza
fi

if command -v fd >/dev/null 2>&1; then
    alias find=fd
fi

if command -v duf >/dev/null 2>&1; then
    alias df=duf
fi

if command -v dust >/dev/null 2>&1; then
    alias du=dust
fi

if [ -d "$HOME/.config/cdpath" ]; then
    export CDPATH=".:$HOME/.config/cdpath:/"
    alias goto="cd -P"
fi

# From https://news.ycombinator.com/item?id=38474106
# Requires fzf, rg and bat.
function frg {
    result=$(rg --ignore-case --color=always --line-number --no-heading "$@" |
    fzf --ansi \
        --color 'hl:-1:underline,hl+:-1:underline:reverse' \
        --delimiter ':' \
        --preview "bat --color=always {1} --theme='Solarized (light)' --highlight-line {2}" \
        --preview-window 'up,60%,border-bottom,+{2}+3/3,~3')
    file=${result%%:*}
    linenumber=$(echo "${result}" | cut -d: -f2)
    if [[ -n "$file" ]]; then
            $EDITOR +"${linenumber}" "$file"
    fi
}

# Windows specifics
if [[ $(uname -r) =~ "microsoft" ]]; then
    open() {
        for file in "$@"
        do
            if [ -f "$file" ]; then
                cmd.exe /C "$file"
            else
                explorer.exe "$file"
            fi
        done
    }

    if command -v "win32yank.exe" >/dev/null 2>&1; then
        alias pbcopy="win32yank.exe -i"
        alias pbpaste="win32yank.exe -o"
    fi
fi
