#!/usr/bin/env bash
alias vimrc="${EDITOR} ${HOME}/.config/nvim/init.vim"
alias run="docker run -it --rm  -v `pwd`:`pwd` $@"
alias tmux="tmux new-session -ADs main"
alias myip-local="myip -local | cut -d ' ' -f2"
alias less="less -r -S -N"
alias zshrc="${EDITOR} ${HOME}/.zshrc"
alias js3="tree -L 3 -I node_modules"

if command -v bat >/dev/null 2>&1; then
    alias cat=bat
else
    if command -v ccat >/dev/null 2>&1; then
        alias cat=ccat
    fi
fi

if [ -d "$HOME/.config/cdpath" ]; then
    export CDPATH=".:$HOME/.config/cdpath:/"
    alias goto="cd -P"
fi

# Windows specifics
if [[ $(uname -r) =~ "microsoft" ]]; then
    open() {
        for file in "$@"
        do
            if [ -f $file ]; then
                cmd.exe /C "$file"
            else
                explorer.exe $file
            fi
        done
    }

    if command -v "win32yank.exe" >/dev/null 2>&1; then
        alias pbcopy="win32yank.exe -i"
        alias pbpaste="win32yank.exe -o"
    fi
fi
