#!/usr/bin/env bash

# SSH
# from https://github.com/triketora/dotfiles/blob/master/bash_profile
export SSH_KEY_PATH="${HOME}/.ssh/id_rsa"
function start_ssh_agent {
	echo "Initialising new SSH agent."
	/usr/bin/ssh-agent | sed 's/^echo/#echo/' >"$HOME/.ssh/environment"
	echo "Success!"
	chmod 600 "$HOME/.ssh/environment"
	. "$HOME/.ssh/environment" >/dev/null
	/usr/bin/ssh-add
}

# Source SSH settings, if applicable
if [ -f "$HOME/.ssh/environment" ]; then
	. "$HOME/.ssh/environment" >/dev/null
	ps -ef | pgrep "${SSH_AGENT_PID}" | grep "ssh-agent$" >/dev/null || {
		start_ssh_agent
	}
else
	start_ssh_agent
fi

export AGE_PUBLIC_KEY="age1xdnnacmr5z3rk4a8avn62vzz8mnzc3xu668k33mn7gj2qe3uavtqgdv2t7"
export SOPS_AGE_RECIPIENTS="$AGE_PUBLIC_KEY"
export SOPS_AGE_KEY_FILE="$HOME/.age.txt"
