#!/usr/bin/env bash
export NVIM_LISTEN_ADDRESS=/tmp/nvimsocket
export CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt

# from https://github.com/triketora/dotfiles/blob/master/bash_profile
SSH_ENV="${HOME}/.ssh/environment"
function start_ssh_agent {
     echo "Initialising new SSH agent..."
     /usr/bin/ssh-agent | sed 's/^echo/#echo/' > "${SSH_ENV}"
     echo "Success!"
     chmod 600 "${SSH_ENV}"
     . "${SSH_ENV}" > /dev/null
     /usr/bin/ssh-add;
}

# Source SSH settings, if applicable
if [ -f "${SSH_ENV}" ]; then
     . "${SSH_ENV}" > /dev/null
     ps -ef | grep ${SSH_AGENT_PID} | grep ssh-agent$ > /dev/null || {
         start_ssh_agent;
     }
else
     start_ssh_agent;
fi
